import type { Metadata } from "next";
import "./globals.css";
import {Inter, Gabarito} from 'next/font/google'
import Provider from "@/components/provider";

const brandFont = Inter({subsets: ["latin"]})


export const metadata: Metadata = {
  title: "Work Dey Here",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body  className={brandFont.className}>
        <Provider>
        <div className="flex flex-col min-h-screen">
        
        <main className="flex-grow">{children}</main>
        </div>
        </Provider>
      </body>
    </html>
  );
}
